-- Populate course_outlines table with initial course outline data
-- This matches course PDFs in the course-pdfs storage bucket with their corresponding courses

INSERT INTO course_outlines (course_slug, course_name, pdf_url, pdf_filename) VALUES
  ('ai-plus--chief-ai-officer', 'AI+ Chief AI Officer', 'ai-chief-ai-officer-course-outline-1500.pdf', 'ai-chief-ai-officer-course-outline-1500.pdf'),
  ('ai-plus--foundation', 'AI+ Foundation', 'ai-foundation-course-outline-1779.pdf', 'ai-foundation-course-outline-1779.pdf'),
  ('ai-plus--government', 'AI+ Government', 'AI+ Government Detailed Curriculum (1).pdf', 'AI+ Government Detailed Curriculum (1).pdf'),
  ('ai-plus--architect', 'AI+ Architect', 'AI+ Architect Detailed Curriculum (1).pdf', 'AI+ Architect Detailed Curriculum (1).pdf'),
  ('ai-plus--business-intelligence', 'AI+ Business Intelligence', 'ai-business-intelligence-course-outline-1933.pdf', 'ai-business-intelligence-course-outline-1933.pdf'),
  ('ai-plus--cloud', 'AI+ Cloud', 'AI+ Cloud Program Detailed Curriculum (4).pdf', 'AI+ Cloud Program Detailed Curriculum (4).pdf'),
  ('ai-plus--customer-service', 'AI+ Customer Service', 'AI+ Customer Service Program Detailed Curriculum (1).pdf', 'AI+ Customer Service Program Detailed Curriculum (1).pdf'),
  ('ai-plus--data', 'AI+ Data', 'AI+ Data Detailed Curriculum (1).pdf', 'AI+ Data Detailed Curriculum (1).pdf'),
  ('ai-plus--data-agent', 'AI+ Data Agent', 'AI+ Data Detailed Curriculum (1).pdf', 'AI+ Data Detailed Curriculum (1).pdf'),
  ('ai-plus--design', 'AI+ Design', 'AI+ Design Detailed Curriculum (1).pdf', 'AI+ Design Detailed Curriculum (1).pdf'),
  ('ai-plus--developer', 'AI+ Developer', 'AI+ Developer Program Detailed Curriculum (2).pdf', 'AI+ Developer Program Detailed Curriculum (2).pdf'),
  ('ai-plus--doctor', 'AI+ Doctor', 'ai-doctor-Detail curriculum.pdf', 'ai-doctor-Detail curriculum.pdf'),
  ('ai-plus--educator', 'AI+ Educator', 'AI+ Educator Program Detailed Curriculum (2).pdf', 'AI+ Educator Program Detailed Curriculum (2).pdf'),
  ('ai-plus--engineer', 'AI+ Engineer', 'AI+ Engineer Detailed Curriculum (1).pdf', 'AI+ Engineer Detailed Curriculum (1).pdf'),
  ('ai-plus--ethical-hacker', 'AI+ Ethical Hacker', 'AI+ Ethical Hacker Detailed Curriculum (1).pdf', 'AI+ Ethical Hacker Detailed Curriculum (1).pdf'),
  ('ai-plus--ethics', 'AI+ Ethics', 'AI+ Ethics Program Detailed Curriculum (1).pdf', 'AI+ Ethics Program Detailed Curriculum (1).pdf'),
  ('ai-plus--everyone', 'AI+ Everyone', 'AI+ Everyone Program Detailed Curriculum (1).pdf', 'AI+ Everyone Program Detailed Curriculum (1).pdf'),
  ('ai-plus--executive', 'AI+ Executive', 'AI+ Executive Program Detailed Curriculum (1).pdf', 'AI+ Executive Program Detailed Curriculum (1).pdf'),
  ('ai-plus--finance', 'AI+ Finance', 'AI+ Finance Detailed Curriculum (1).pdf', 'AI+ Finance Detailed Curriculum (1).pdf'),
  ('ai-plus--healthcare', 'AI+ Healthcare', 'AI+ Healthcare Detailed Curriculum (1).pdf', 'AI+ Healthcare Detailed Curriculum (1).pdf'),
  ('ai-plus--legal', 'AI+ Legal', 'AI+ Legal Detailed Curriculum (1).pdf', 'AI+ Legal Detailed Curriculum (1).pdf'),
  ('ai-plus--legal-agent', 'AI+ Legal Agent', 'AI+ Legal Detailed Curriculum (1).pdf', 'AI+ Legal Detailed Curriculum (1).pdf'),
  ('ai-plus--marketing', 'AI+ Marketing', 'AI+ Marketing Program Detailed Curriculum (1).pdf', 'AI+ Marketing Program Detailed Curriculum (1).pdf'),
  ('ai-plus--network', 'AI+ Network', 'ai-network-course-outline-1403.pdf', 'ai-network-course-outline-1403.pdf'),
  ('ai-plus--product-manager', 'AI+ Product Manager', 'AI+ Product Manager Detailed Curriculum.pdf', 'AI+ Product Manager Detailed Curriculum.pdf'),
  ('ai-plus--project-manager', 'AI+ Project Manager', 'AI+ Project Manager Program Detailed Curriculum (1).pdf', 'AI+ Project Manager Program Detailed Curriculum (1).pdf'),
  ('ai-plus--prompt-engineer-level-2', 'AI+ Prompt Engineer Level 2', 'AI+ Prompt Engineer Level 2 Detailed Curriculum (1).pdf', 'AI+ Prompt Engineer Level 2 Detailed Curriculum (1).pdf'),
  ('ai-plus--quality-assurance', 'AI+ Quality Assurance', 'ai-quality-assurance-course-outline-1921.pdf', 'ai-quality-assurance-course-outline-1921.pdf'),
  ('ai-plus--quantum', 'AI+ Quantum', 'AI+ Quantum Detailed Curriculum (2).pdf', 'AI+ Quantum Detailed Curriculum (2).pdf'),
  ('ai-plus--real-estate', 'AI+ Real Estate', 'ai-real estate-Detailed Curriculum.pdf', 'ai-real estate-Detailed Curriculum.pdf'),
  ('ai-plus--researcher', 'AI+ Researcher', 'AI+ Researcher Detailed Curriculum (2).pdf', 'AI+ Researcher Detailed Curriculum (2).pdf'),
  ('ai-plus--robotics', 'AI+ Robotics', 'AI+ Robotics Detailed Curriculum (2) (1).pdf', 'AI+ Robotics Detailed Curriculum (2) (1).pdf'),
  ('ai-plus--sales', 'AI+ Sales', 'AI+ Sales Detailed Curriculum (1).pdf', 'AI+ Sales Detailed Curriculum (1).pdf'),
  ('ai-plus--security-compliance', 'AI+ Security Compliance', 'AI+ Security Compliance Detailed Curriculum (1).pdf', 'AI+ Security Compliance Detailed Curriculum (1).pdf'),
  ('ai-plus--security-level-1', 'AI+ Security Level 1', 'AI+ Security Level 1 Detailed Curriculum.pdf', 'AI+ Security Level 1 Detailed Curriculum.pdf'),
  ('ai-plus--security-level-2', 'AI+ Security Level 2', 'AI+ Security Level 2 Detailed Curriculum.pdf', 'AI+ Security Level 2 Detailed Curriculum.pdf'),
  ('ai-plus--smart-city', 'AI+ Smart City', 'ai-smart-city-course-outline-1959.pdf', 'ai-smart-city-course-outline-1959.pdf'),
  ('ai-plus--supply-chain', 'AI+ Supply Chain', 'ai-supply-chain-Detailed Curriculum.pdf', 'ai-supply-chain-Detailed Curriculum.pdf'),
  ('ai-plus--vibe-coder', 'AI+ Vibe Coder', 'AI+ Vibe Coder Curriculum.pdf', 'AI+ Vibe Coder Curriculum.pdf'),
  ('blockchain-plus--architect', 'Blockchain+ Architect', 'Blockchain+ Architect Detailed Curriculum (1).pdf', 'Blockchain+ Architect Detailed Curriculum (1).pdf'),
  ('blockchain-plus--business', 'Blockchain+ Business', 'Blockchain+ Business Detailed Curriculum (1).pdf', 'Blockchain+ Business Detailed Curriculum (1).pdf'),
  ('blockchain-plus--developer', 'Blockchain+ Developer', 'Blockchain+ Developer Program Detailed Curriculum.pdf', 'Blockchain+ Developer Program Detailed Curriculum.pdf'),
  ('blockchain-plus--engineer', 'Blockchain+ Engineer', 'Blockchain+ Engineer Detailed Curriculum (1).pdf', 'Blockchain+ Engineer Detailed Curriculum (1).pdf'),
  ('blockchain-plus--essential', 'Blockchain+ Essential', 'Blockchain+ Essential Detailed Curriculum (1).pdf', 'Blockchain+ Essential Detailed Curriculum (1).pdf'),
  ('blockchain-plus--executive', 'Blockchain+ Executive', 'Blockchain+ Executive Program Detailed Curriculum.pdf', 'Blockchain+ Executive Program Detailed Curriculum.pdf'),
  ('blockchain-plus--security', 'Blockchain+ Security', 'Blockchain+ Security Detailed Curriculum (1).pdf', 'Blockchain+ Security Detailed Curriculum (1).pdf'),
  ('iot-plus--architect', 'IoT+ Architect', 'IoT+ Architect Detailed Curriculum (1).pdf', 'IoT+ Architect Detailed Curriculum (1).pdf'),
  ('iot-plus--business', 'IoT+ Business', 'IoT+ Business Program Detailed Curriculum (2).pdf', 'IoT+ Business Program Detailed Curriculum (2).pdf'),
  ('iot-plus--developer', 'IoT+ Developer', 'IoT+ Developer Program Detailed Curriculum (2).pdf', 'IoT+ Developer Program Detailed Curriculum (2).pdf'),
  ('iot-plus--security', 'IoT+ Security', 'IoT+ Security Detailed Curriculum (1).pdf', 'IoT+ Security Detailed Curriculum (1).pdf')
ON CONFLICT (course_slug) DO NOTHING;