// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lzxlamelyfrfrhrgfigb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx6eGxhbWVseWZyZnJocmdmaWdiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk2ODE3MjAsImV4cCI6MjA2NTI1NzcyMH0.MoKzqzJXjHuN5b8ZXD705xYg-YRuw28G-X22FxUbn-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);